### ISSUE TITLE
Proper Alignments  of boxes

### ISSUE THREAD

**Issue by diksha0149** [VG-1/PlaylistAdda#113]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
     Improper alignment not giving a better look to website
- How will this change help?
   I can resolve this issue by adding css
- What is the motivation? 
   My motivation is to make website UI better

#### Description
Please try answering few of those questions
- What changes have to be introduced?
 all boxes to have same alignment
- Will this be a breaking change?
No
- How could it be implemented/designed?
It can be simply done by adding css

Please  assign me this issue under Hacktoberfest2022?

**Comment by VG-1** [comment]
@diksha0149 assigned this to you.

Kindly make sure that Spotify and YouTube playlists are separated only.
