### ISSUE TITLE
Fix the css of Header

### ISSUE THREAD

**Issue by VG-1** [VG-1/PlaylistAdda#16]

**Comment by sunidhisachan** [comment]
@VG-1 I can do this . Please assign this to me.

**Comment by VG-1** [comment]
sure
@sunidhisachan assigning it to you.

**Comment by sunidhisachan** [comment]
hew @VG-1 what changes do you want in header . Can you elaborate?

**Comment by VG-1** [comment]
hey @sunidhisachan currently header is not that cool.
You can add animation, hover-effect or something like that.
