### ISSUE TITLE
Fix the alignment of some cards and broken links

### ISSUE THREAD

**Issue by VG-1** [VG-1/PlaylistAdda#173]
The div tag of some cards is misplaced align them and fix some of the broken links

**Comment by sayan404** [comment]
assign me @VG-1

**Comment by VG-1** [comment]
Sure go ahead @sayan404

**Comment by Lakhwinderr** [comment]
Hey, I did the task, Check the PR.

**Comment by GeeteshMehto** [comment]
Hello sir, please assign this issue to me as i already worked on this kind of problem in past and has a great experience.

**Comment by VG-1** [comment]
Hey @GeeteshMehto this issue has been solved you can work on another issue
