### ISSUE TITLE
Want to add a playlist

### ISSUE THREAD

**Issue by sayan404** [VG-1/PlaylistAdda#188]
## Guide
Here are a few steps you can follow to write an AsyncAPI blog post:

1. After getting feedback on the issue, fork the `website` [repository](https://github.com/asyncapi/website) or open it in Gitpod. You can do that by prefixing the issue URL with `gitpod.io/#`.
1. Run the command `npm run write:blog`.
1. Run the website by using instructions from the README to test your changes.
1. Open a PR with your blog post and test your changes with a preview of the site on Netlify. If you use Gitpod, it will create a fork of the website repo for you before you create a PR.
1. Maintainers reviewing the article (e.g., language, images) may ask for improvements.
1. Once it's merged, it will be available live in production. :rocket:

We encourage you to write a blog post and share it with the community. We can't wait to read it :smile:!

**Comment by sayan404** [comment]
pls assign me this issue @VG-1

**Comment by VG-1** [comment]
Sure
