### ISSUE TITLE
Add a top-down button just like the bottom up button 

### ISSUE THREAD

**Issue by VG-1** [VG-1/PlaylistAdda#199]

**Comment by HammadKhaan** [comment]
@VG-1 assign this issue to me please. And explain it a little bit more.

**Comment by VG-1** [comment]
Sure, check-out 
https://vg-1.github.io/PlaylistAdda/

There is a down-top button, by clicking on it one can directly go to the top of the website.

Similarly there should be a button by clicking on which one can directly reach to bottom of the website

**Comment by Kamlesh72** [comment]
I would like to work on this issue Or is it already assigned?

**Comment by thisisamandang** [comment]
I would like to work this issue. Please assign this to me if not assigned already.

**Comment by VG-1** [comment]
Sure, check-out 
https://vg-1.github.io/PlaylistAdda/

There is a down-top button, by clicking on it one can directly go to the top of the website.

Similarly there should be a button by clicking on which one can directly reach to bottom of the website 

    @HammadKhaan do you want to work on this issue?

**Comment by thisisamandang** [comment]
@VG-1 I want to work on this top-down button issue, Assign this to me if not assigned already

**Comment by VG-1** [comment]
Hey @Kamlesh72 do you want to work on it?

**Comment by Kamlesh72** [comment]
Yes I would love to work on it.

**Comment by shell-raiser** [comment]
Hey, I have already done it here at #222
