### ISSUE TITLE
Make a login authentication page for every user

### ISSUE THREAD

**Issue by VG-1** [VG-1/PlaylistAdda#20]

**Comment by alvinokafor** [comment]
Hi @VG-1 , I would love to take this issue up

**Comment by VG-1** [comment]
hey @alvinokafor sure assigning this to you.

**Comment by alvinokafor** [comment]
Thanks 🙏

**Comment by alvinokafor** [comment]
Hi @VG-1, I Do I need to add OAuth authentication, or should I just create the page with html and css

**Comment by VG-1** [comment]
Just create a page for now.

**Comment by VG-1** [comment]
Also please attach some video or gif in comment here

**Comment by alvinokafor** [comment]
A video? like in the page?

**Comment by VG-1** [comment]
Nope,in your PR so that I can a bit overview about it.
@alvinokafor are you working on it?

**Comment by alvinokafor** [comment]
Yea, you've already reviewed and merged the pull request
