### ISSUE TITLE
I want to improve the footer of the website, to make it look more better, it will enhance the look of the website, pls assign this issue to me.

### ISSUE THREAD

**Issue by shivi11g** [VG-1/PlaylistAdda#207]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
- How will this change help?
- What is the motivation? 

#### Description
Please try answering few of those questions
- What changes have to be introduced?
- Will this be a breaking change?
- How could it be implemented/designed?

**Comment by VG-1** [comment]
Hey @shivi11g sure
What are the changes you want to make in the footer?

**Comment by shivi11g** [comment]
In the footer there are no social media handles, also no copyright line, So I'll add that also I'll add some margin, padding to the footer, and I can also add an animated footer, if it will good, right now it is very simple.

**Comment by VG-1** [comment]
Yeah sure go ahead @shivi11g :)
Assigning it to you.
