### ISSUE TITLE
Design a cool logo for the website and add it to title.

### ISSUE THREAD

**Issue by VG-1** [VG-1/PlaylistAdda#21]

**Comment by mgilberties** [comment]
Please can you assign this to me?

**Comment by VG-1** [comment]
sure :)

**Comment by mgilberties** [comment]
@VG-1  Thank you. I have opened PR: https://github.com/VG-1/PlaylistAdda/pull/26 
Have a look and let me know what you think.

**Comment by impranavtg** [comment]
@VG-1 take a look [at]([url](url)) this logo. Is it okay?
![PlayListAdda-Logo](https://user-images.githubusercontent.com/83161133/194696171-09d77aa2-a8ec-40ab-a4f9-4c93b88fea22.jpg)
