### ISSUE TITLE
A visually better scroll bar 

### ISSUE THREAD

**Issue by thisisamandang** [VG-1/PlaylistAdda#210]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
ans: The UI of the project will be hugely affected in a positive way if we make this change.

- How will this change help?
ans:  It will give the user a visually aesthetic experience.

- What is the motivation? 
I am starting out in open Source and want to contribute and hone my skills and this particular feature is best- suited for that. 

#### Description
Please try answering few of those questions

- What changes have to be introduced?
- ans: Scroll bar will be made visually attractive.

- Will this be a breaking change?
ans: No this is a fairly safe change that can be made.

- How could it be implemented/designed?
ans: I can make it using webkit-scrollbar properties in CSS

**Comment by VG-1** [comment]
hey @thisisamandang thanks for pulling it up.
Sure you can go ahead and work on it.
Assigned it to you.
