### ISSUE TITLE
Fix all the cards of the playlists with proper alignment.

### ISSUE THREAD

**Issue by VG-1** [VG-1/PlaylistAdda#212]

**Comment by Gunika2002** [comment]
hi @VG-1 I would like to work on this please assign me

**Comment by VG-1** [comment]
Sure @Gunika2002 go ahead.
Assigning it to you.

Make sure YouTube Playlist Cards and Spotify PlayList Cards are shown separately.
Fixing some div tags should resolve the issue.

**Comment by kashish0604** [comment]
hey @VG-1 please assign this issue to me i can work on it

**Comment by Gunika2002** [comment]
> Sure @Gunika2002 go ahead. Assigning it to you.
> 
> Make sure YouTube Playlist Cards and Spotify PlayList Cards are shown separately. Fixing some div tags should resolve the issue.

Alright!! almost done will make the pr soon

**Comment by VG-1** [comment]
> hey @VG-1 please assign this issue to me i can work on it

Hey @kashish0604 this issue is already assigned, you can work on any other issue :)

**Comment by thisisamandang** [comment]
@Gunika2002 I've fixed this issue, You just have to close a few div tags, In case you need help i'm up for it

**Comment by Gunika2002** [comment]
> @Gunika2002 I've fixed this issue, You just have to close a few div tags, In case you need help i'm up for it

I have already sent the pr and it has been merged. Thanks for the offer anyways.

**Comment by thisisamandang** [comment]
Okay. Great!
