### ISSUE TITLE
Fix the alignment of cards of every playlist.

### ISSUE THREAD

**Issue by VG-1** [VG-1/PlaylistAdda#227]
Try checking some <div> if they are at right place or not.

**Comment by VG-1** [comment]
@thisisamandang want to work on it?

**Comment by thisisamandang** [comment]
Yes!!

**Comment by VG-1** [comment]
go ahead.

**Comment by thisisamandang** [comment]
Yeah, I just checked

**Comment by thisisamandang** [comment]
@VG-1 Hey, Can you merge this PR I made , From what I understand you probably have authorization to do that right?  [https://github.com/bluelearn-open-source/blue-quotes/pull/124](url)
