### ISSUE TITLE
Fix the responsiveness of placeholder of search bar.

### ISSUE THREAD

**Issue by VG-1** [VG-1/PlaylistAdda#228]

**Comment by geeky01adarsh** [comment]
I want to work on this issue. Please assign it to me.

**Comment by divya-nshi** [comment]
I would like to work on this issue could u please assign it to me?

**Comment by VG-1** [comment]
Hey @geeky01adarsh you can work on it.
Assigned it to you.

**Comment by VG-1** [comment]
@divya-nshi you can check out the 5th step of readme.md, hope it helps

This issue has been assigned as he asked first so.

**Comment by divya-nshi** [comment]
Yep Thank u :)... I'll add my playlist and will try to figure out 235 issue

**Comment by gajanansr** [comment]
please assign me this
