### ISSUE TITLE
Make a separate js file for javascript code.

### ISSUE THREAD

**Issue by VG-1** [VG-1/PlaylistAdda#30]

**Comment by Sammydepoj** [comment]
Hi, I'll like to work on this. 
Kindly assign it to me

**Comment by VG-1** [comment]
Sure @Sammydepoj 
Assigning this to you.

**Comment by Sammydepoj** [comment]
Thank you. Will start working on it asap

**Comment by Ayush-Khandelwal28** [comment]
If the issue is still open, I would like to contribute, please assign it to me @VG-1

**Comment by Sammydepoj** [comment]
Hi @Ayush-Khandelwal28 , I've worked on the issue. Thank you.
