### ISSUE TITLE
Make header and footer responsive.

### ISSUE THREAD

**Issue by VG-1** [VG-1/PlaylistAdda#4]

**Comment by hamzicio** [comment]
Hey can i work on this issue? @VG-1

**Comment by VG-1** [comment]
sure @hamzicio go ahead.
Assigning it to you :)

**Comment by Pallavibahekar** [comment]
Could you please assign me this issue @VG-1 ?

**Comment by VG-1** [comment]
Hey @Pallavibahekar the issue is resolved.
You can create a new issue to add a new feature to the website.
