### ISSUE TITLE
improve the code and fix broken links.

### ISSUE THREAD

**Issue by VG-1** [VG-1/PlaylistAdda#64]
-fix broken spotify links
-footer is in between some playlists bring it to the bottom of the website.

**Comment by harsitagarwalla187** [comment]
Can you assign it to me?

**Comment by VG-1** [comment]
Sure go ahead:)

**Comment by harsitagarwalla187** [comment]
@VG-1 All links are working now.
Footer is been in right place and organised all the unorganised cards.
Can i now make a PR?

**Comment by harsitagarwalla187** [comment]
@VG-1 All links are working now.
Footer is been in right place and organised all the unorganised cards.

**Comment by VG-1** [comment]
Thanks @harsitagarwalla187 :)
Glad that you have contributed.
Do share it with your friends.
