### ISSUE TITLE
Want to Add Bottom to Top button

### ISSUE THREAD

**Issue by grraghav120** [VG-1/PlaylistAdda#89]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
- for user friendly we can add bottom to top button
- How will this change help?
- User can easily go to top from bottom
- What is the motivation? 

#### Description
Please try answering few of those questions
- What changes have to be introduced?
-  Its just an example how button looks like
![gg](https://user-images.githubusercontent.com/96789493/194696814-df276eda-50c2-47d1-89e1-b5a8a9f7f38a.jpg)

- Will this be a breaking change?
- How could it be implemented/designed?

**Comment by grraghav120** [comment]
Kindly assign me under hacktoberfest-accepted

**Comment by VG-1** [comment]
Great
 assigned it to you :)
