### ISSUE TITLE
Hide scroll to top button when already on top of the page

### ISSUE THREAD

**Issue by ashutoshkrris** [VG-1/PlaylistAdda#97]
#### Describe the bug
The Scroll to top button doesn't make any sense when user is already on the top of the page. Even if it's clicked, it won't scroll to anywhere.

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:
1. Go to https://vg-1.github.io/PlaylistAdda/
2. Click on the Scroll to top button when already on the top of the page.
3. See the bug

- Screenshots
- Link to GitHub repository with project that has issues
- Files that can help reproduce the issue, like your AsyncAPI file, either paste inside the issue in a code block or in a sharable [gist](https://gist.github.com/)

#### Expected behavior
The scroll to top button should be visible only when user scrolls down.

**Comment by MuhammadAakash** [comment]
I would like to work on this issue. 
Please assign it to me.

**Comment by VG-1** [comment]
Hey @MuhammadAakash 

I am glad that you want to work on it, but as @ashutoshkrris has raised the issue so I am assigning this to him.

**Comment by VG-1** [comment]
@ashutoshkrris you can work on it.

**Comment by MuhammadAakash** [comment]
@VG-1  
Sure 
No Problem
